// Code generated by templ - DO NOT EDIT.

// templ: version: 0.2.432
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Layout() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"fr\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var2 := `Marienbad`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</title><link rel=\"stylesheet\" href=\"app.css\"></head><body class=\"min-h-screen bg-background text-foreground antialiased font-sans\"><noscript><p class=\"m-4 p-3 rounded-md bg-amber-100 text-amber-900 border border-amber-300 text-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var3 := `Ce jeu nécessite JavaScript et WebAssembly.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></noscript><div id=\"wasm-error\" class=\"hidden m-4 p-3 rounded-md bg-amber-100 text-amber-900 border border-amber-300 text-center text-sm\"></div><main class=\"max-w-3xl mx-auto px-6 py-12\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ModeSelector().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = GameView().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<footer class=\"mt-12 text-center text-xs text-muted-foreground\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var4 := `Go + WebAssembly · hors ligne · variante misère`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</footer></main><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var5 := ` Fireworks canvas (overlay, only visible on victory) `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div id=\"fireworks-overlay\" class=\"fixed inset-0 pointer-events-none hidden z-50\" aria-hidden=\"true\"></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := ` Game-over overlay (loss against AI) `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div id=\"gameover-overlay\" class=\"game-over-overlay hidden\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"gameover-text\"><div class=\"game-over-stage\"><h1 id=\"gameover-text\" class=\"retro-text\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var7 := `GAME OVER`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><p id=\"gameover-sub\" class=\"game-over-sub\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var8 := `L'ordinateur t'a battu.`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><div class=\"flex justify-center gap-2 mt-8\"><button id=\"gameover-close\" class=\"inline-flex items-center justify-center h-9 px-4 rounded-md border border-border text-sm font-medium bg-card text-foreground hover:bg-muted cursor-pointer transition-colors\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var9 := `Fermer`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button> <button id=\"gameover-replay\" class=\"inline-flex items-center justify-center h-9 px-4 rounded-md text-sm font-medium bg-primary text-primary-foreground hover:opacity-90 cursor-pointer transition-opacity\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var10 := `Rejouer`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var10)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div></div></div><!--")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var11 := ` Victory modal (no backdrop — fireworks behind must remain visible) `
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var11)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("--><div id=\"victory-modal\" class=\"fixed inset-0 hidden z-[60] flex items-center justify-center pointer-events-none\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"victory-title\"><div class=\"bg-card border border-border rounded-xl shadow-2xl p-8 max-w-md mx-4 text-center pointer-events-auto\"><div class=\"text-5xl mb-4\" aria-hidden=\"true\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var12 := `🎉`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var12)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><h2 id=\"victory-title\" class=\"text-2xl font-semibold mb-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var13 := `Victoire !`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var13)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h2><p id=\"victory-message\" class=\"text-muted-foreground mb-6\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var14 := `…`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var14)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><div class=\"flex justify-center gap-2\"><button id=\"victory-close\" class=\"inline-flex items-center justify-center h-9 px-4 rounded-md border border-border text-sm font-medium bg-transparent hover:bg-muted cursor-pointer\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var15 := `Fermer`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button> <button id=\"victory-replay\" class=\"inline-flex items-center justify-center h-9 px-4 rounded-md text-sm font-medium bg-primary text-primary-foreground hover:opacity-90 cursor-pointer\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var16 := `Rejouer`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button></div></div></div><script src=\"fireworks.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var17 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var17)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var18 := `
		(function () {
			var fw = null;
			var overlay = document.getElementById("fireworks-overlay");
			var modal = document.getElementById("victory-modal");
			var titleEl = document.getElementById("victory-title");
			var msgEl = document.getElementById("victory-message");

			function stop() {
				if (fw) { try { fw.stop(); } catch (e) {} fw = null; }
				overlay.classList.add("hidden");
				modal.classList.add("hidden");
			}

			window.marianbadCelebrate = function (title, message) {
				titleEl.textContent = title || "Victoire !";
				msgEl.textContent = message || "";
				overlay.classList.remove("hidden");
				modal.classList.remove("hidden");

				// Resolve which constructor the UMD bundle exposes.
				var FW = (window.Fireworks && window.Fireworks.Fireworks)
					|| window.Fireworks
					|| null;
				if (!FW) {
					console.warn("fireworks-js library not loaded");
					return;
				}

				// Defer to next animation frame so the overlay has a real
				// layout size before Fireworks reads container.clientWidth.
				requestAnimationFrame(function () {
					try {
						fw = new FW(overlay, {
							hue: { min: 0, max: 360 },
							acceleration: 1.02,
							intensity: 28,
							explosion: 7,
							particles: 90,
							traceSpeed: 12,
							delay: { min: 22, max: 38 },
							opacity: 0.4,
							sound: { enabled: false }
						});
						fw.start();
						setTimeout(function () {
							if (fw) { try { fw.stop(); } catch (e) {} }
							overlay.classList.add("hidden");
						}, 7000);
					} catch (e) {
						console.warn("fireworks failed:", e);
					}
				});
			};

			window.marianbadHideVictory = stop;

			document.getElementById("victory-close").addEventListener("click", stop);
			document.getElementById("victory-replay").addEventListener("click", function () {
				stop();
				var btn = document.getElementById("btn-restart");
				if (btn) btn.click();
			});

			// --- Game Over overlay (loss) ---
			var go = document.getElementById("gameover-overlay");
			var goSub = document.getElementById("gameover-sub");
			function hideGameOver() { go.classList.add("hidden"); }
			window.marianbadGameOver = function (subtitle) {
				goSub.textContent = subtitle || "L'ordinateur t'a battu.";
				go.classList.remove("hidden");
			};
			window.marianbadHideGameOver = hideGameOver;
			document.getElementById("gameover-close").addEventListener("click", hideGameOver);
			document.getElementById("gameover-replay").addEventListener("click", function () {
				hideGameOver();
				var btn = document.getElementById("btn-restart");
				if (btn) btn.click();
			});
		})();
		`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var18)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script src=\"wasm_exec.js\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var19 := ``
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var19)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script><script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var20 := `
			(function () {
				if (typeof WebAssembly === "undefined" || typeof Go === "undefined") {
					document.getElementById("wasm-error").classList.remove("hidden");
					document.getElementById("wasm-error").textContent = "WebAssembly indisponible.";
					return;
				}
				const go = new Go();
				const load = WebAssembly.instantiateStreaming
					? WebAssembly.instantiateStreaming(fetch("main.wasm"), go.importObject)
					: fetch("main.wasm").then(r => r.arrayBuffer()).then(b => WebAssembly.instantiate(b, go.importObject));
				load.then(r => go.run(r.instance)).catch(err => {
					console.error("WASM load failed:", err);
					const el = document.getElementById("wasm-error");
					el.textContent = "Erreur de chargement : " + err.message;
					el.classList.remove("hidden");
				});
			})();
		`
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
